export function generateClaudeMd(config) {
  const agentTable = config.agents
    .map(
      (a) =>
        `| ${a.name} | ${a.role} | \`.claude-team/agents/${a.name}.md\` | \`.claude-team/tasks/${a.name}-inbox.json\` |`
    )
    .join("\n");

  return `# ${config.projectName} — Claude Team Config

> Auto-generated by claude-team. Edit manually or re-run \`claude-team init\`.

## Project Overview
- **Goal**: ${config.projectGoal}  
- **Type**: ${config.projectType}  
- **Stack**: ${config.techStack}  
- **Coordination**: ${config.coordination.taskStyle}

## Team Structure

| Agent | Role | Instructions | Inbox |
|-------|------|-------------|-------|
| orchestrator | Project Orchestrator | \`.claude-team/ORCHESTRATOR.md\` | \`.claude-team/tasks/orchestrator-inbox.json\` |
${agentTable}

## How to Launch the Team

Open one terminal per agent, each in the project root:

\`\`\`bash
# Terminal 1 — Orchestrator
claude
# Then tell Claude: "Read CLAUDE.md and .claude-team/ORCHESTRATOR.md to understand your role"

${config.agents
  .map(
    (a, i) => `# Terminal ${i + 2} — Agent: ${a.name}
claude
# Then tell Claude: "Read CLAUDE.md and .claude-team/agents/${a.name}.md"`
  )
  .join("\n\n")}
\`\`\`

## Coordination Files

\`\`\`
.claude-team/
├── ORCHESTRATOR.md          # Orchestrator instructions
├── NOTES.md                 # Shared notes across agents
├── config.json              # Team configuration
├── agents/
│   ${config.agents.map((a) => `└── ${a.name}.md`).join("\n│   ")}
├── tasks/
│   ├── master.json          # Overall task tracker
│   ├── queue.json           # Unassigned task queue
│   ├── orchestrator-inbox.json
│   ${config.agents.map((a) => `├── ${a.name}-inbox.json\n│   ├── ${a.name}-outbox.json\n│   └── ${a.name}-status.json`).join("\n│   ")}
└── logs/                    # Agent activity logs
\`\`\`

## Quick Commands

\`\`\`bash
claude-team status   # See what each agent is doing (terminal)
claude-team office   # Live visual office view (browser)
claude-team add      # Add a new agent to the team
claude-team archive  # Archive docs when the project is done
\`\`\`

---
_Generated: ${new Date().toISOString()}_
`;
}